module.exports = {
  trailingComma: 'all',
  tabWidth: 2,
  printWidth: 200,
  arrowParens: 'always',
  bracketSpacing: true,
  semi: true,
  singleQuote: true,
  jsxSingleQuote: false,
  bracketSameLine: true,
  singleAttributePerLine: true,
  plugins: ['prettier-plugin-tailwindcss'],
  tailwindAttributes: ['className'],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
};
